---
  engines:
    duplication:
      enabled: true
      config:
        languages:
          javascript:
            mass_threshold: 90
    eslint:
      enabled: true
    fixme:
      enabled: true
  ratings:
    paths:
    - "**.js"
  exclude_paths:
  - test/
  - gulpfile.js
