language: node_js
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '8'
- '9'
before_install:
- "$CXX --version"
- npm install
after_script:
- codeclimate-test-reporter < reports/lcov.info
deploy:
- provider: releases
  api_key:
    secure: Ak2rWnFO5Hlu5Va5btfau1jZGYmfIyPrvaWO3rh/CphxkM7wv9cmYy5pFtWbyFLaEY0uiCV4B+gT1G5rcjiYqrzgQ9FFHBy2J2MsUTvaVzCUXGPFr6razkDDUsEf8fv+LMnjsS0V29ElTS7/46XCRsHPr3z+t4fdXCEQPmcHmc2uaL7rDsECNnxmkEEffMyF+at/Rvz5xXAr7btLalbnaEBpSMWCZWjiPtdKjSZXXJnnQ2vgqCYBNrVz706JxtFfQAj86TiBPR6TFELxZpdrgT4oper47QQTNiMgRJA6VUbeTvkgivNjNF61eAFrojkgwORJKhpg5mUEu4f0T/RSsmJf9oOg+fvA/V0jczjE8R99ILmPX2cTL12+V2AiXPeUH9+fsKVVC2IYyMGwLhDbwE6TQzV1gdjwhBSnfeF6Cz6rqJqP0ePAn/s3ndrVLUKpc+DHPTbEvZlXO5F82J0WaaC16T6SDI9+iN/j7mrpa7xLTmTmx+xlZPSUaCXuyiGUt3xgr10DyiwmmcuhPgmzUDMfaNU534uMXs17096i12tV5VHKSZaHcdCw0ai+VCMRViq7Bk2c5od5oIowCuCpwtxyOun0aqt2AKxHihkEhrb94SQmXMIM5ZJkruFD7FOgmA7hUN4SDlNU8EqLNF4876hrlL1IBaf5cF5MeOX2JtY=
  on:
    repo: raveljs/ravel-steam-auth-provider
    tags: true
    node: '8'
- provider: npm
  email: robot@raveljs.com
  tag: latest
  api_key:
    secure: zCndhEXZ88s1/lLR2UGMCmHja1LtkFqy5PIFy/tRDhJr+HHMFbPxRLlExNWGH7mvvlV7VJx1B4u+h3Fvf/Ny5kXOm/J86HNxjYh9utcIeZ41MHEz3jqEA3DEfFr+FkWMp/RE+LX/dZ1IrNJBq6SD5Xx1DcM/V74jm1DaKUspA/EqJ4uEij8VbCM0WYuTqHKRwKT/s4wC9yEZzMy9Nhe+26v23aFQuvD938xRhF1kPzVKG7/ZAHuzFMa2ud36VgbW21FrAGqQ3uR0FBzQe+T/MF4oGyMdbUpPo7YrV91nG6nYXmm6p1FeuUT2o3up4+eWjDA2PAgd3LzyCD7LiFA4iZS7uNcadQYNtkpIfPozW25j99ZTqxfGGPBIlYo2A/SRJGdcKytV9DUXd5nOcIthRpxVhQvfCkRywA3rhpcPTn3tlQivhKfsxexLU0WWNdbO/0zD56DVet0Sa7gzETQJ7tcr+t1Ru4rWTcTGDAV1e+54+5wnbHDsrIFydF4t/G/IqU0B+EoUCZcNP02amP5GhrNRvqui46p/pk2c35g4zVuaEWdY2lXI0SkEXGhgGnFwGEb/rlcNLKXoFM6RWv1Pgb6iQscE1tYMmluMfBCGQHbzH/b5Ebos4nWEsGMDpjDgtalkepSm81KSQkxO8196iakemGkuIx3LZJb33sdV3hc=
  on:
    repo: raveljs/ravel-steam-auth-provider
    tags: true
    node: '8'
